# Generated by Django 5.0.3 on 2024-04-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_dateofjoin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dateofjoin',
            field=models.DateField(null=True),
        ),
    ]
